FROM rust:1.89-slim

# zstd for zstdcat; sqlite dev libs to build sqlx driver fast; bash for scripts
RUN apt-get update \
 && apt-get install -y --no-install-recommends zstd ca-certificates bash libsqlite3-dev pkg-config \
 && rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/local/cargo/bin:/usr/local/rustup/bin:${PATH}"

# hot reload
RUN cargo install cargo-watch

WORKDIR /app
